
//import ModeloDAO.DatosPDAO;
//import ModeloVO.DatosPVO;
//import java.util.ArrayList;
//import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class ActualizarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarUsuario
//     */
//    public ActualizarUsuario() {
//        initComponents();
//        setLocationRelativeTo(null);
//        
//        listaDatos();
//          
//         
//    }
    
     public void listaDatos() {
//        DatosPVO datpVO = new DatosPVO();
//        DatosPDAO datpDAO = new DatosPDAO();
//        //TABLA 
//        ArrayList<DatosPVO> lista = datpDAO.listar();
//
//        DefaultTableModel modelo = new DefaultTableModel();
//        Object[] productos = new Object[8];
//        modelo = (DefaultTableModel) Tabla.getModel();
//
//        for (int i = 0; i < lista.size(); i++) {
//            //PRIMERO EXTRAO 
//            datpVO = lista.get(i);
//
//            productos[0] = datpVO.getDatId();
//            productos[1] = datpVO.getUsuId();
//            productos[2] = datpVO.getDatNombre();
//            productos[3] = datpVO.getDatApellido();
//            productos[4] = datpVO.getDatTipo();
//            productos[5] = datpVO.getDatNumero();
//            productos[6] = datpVO.getDatTelefono();
//            productos[7] = datpVO.getDatCorreo();
//            modelo.addRow(productos);
//
//        }
//
//        Tabla.setModel(modelo);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        buttonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        resultado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 550));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ACTUALIZAR PERFIL ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 20, 270, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 120, 50, 30);
        getContentPane().add(textNombre);
        textNombre.setBounds(190, 120, 230, 30);

        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBuscar);
        buttonBuscar.setBounds(450, 120, 70, 30);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATID", "USUID", "NOMBRE", "APELLIDO", "TIPOID", "NUMEROID", "TELEFONO", "CORREO"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 270, 900, 100);
        getContentPane().add(resultado);
        resultado.setBounds(70, 180, 440, 60);

        jButton1.setText("Volver al Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(443, 400, 110, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
//        String datNombre = textNombre.getText();
//        System.out.println(datNombre);
//        
//        DatosPVO datpVO = new DatosPVO();
//        DatosPDAO datpDAO = new DatosPDAO();
//
//
//        datpVO = datpDAO.consultarNombre(datNombre);
//        if (datpVO != null) {
//
//            JOptionPane.showMessageDialog(null, "Desea modificar datos");
//            EditarPerfil editar = new EditarPerfil();
//            editar.setVisible(true);
//            dispose();
//
//        } else {
//            resultado.setText("El Usuario NO existe");
//
//        }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        Menu menu = new Menu();
//        menu.setVisible(true);
//        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ActualizarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel resultado;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
