
import ModeloDAO.CategoriaDAO;
import ModeloDAO.VehiculoDAO;
import ModeloVO.CategoriaVO;
import ModeloVO.VehiculoVO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author usuario
 */
public class ConsultarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarVehiculo
     */
    public ConsultarVehiculo() {
        initComponents();
        setLocationRelativeTo(null);
        //METODOS DE LISTAR CATEGORIA Y DATOS
        ListarVehiculos();
        listarCategoria();

    }
//REALIZAR LA TABLA
    public void ListarVehiculos() {
        VehiculoVO vehVO = new VehiculoVO();
        VehiculoDAO vehDAO = new VehiculoDAO();
        //TABLA 
        ArrayList<VehiculoVO> lista = vehDAO.listar();

        DefaultTableModel modelo = new DefaultTableModel();
        Object[] productos = new Object[7];
        modelo = (DefaultTableModel) Tabla.getModel();

        for (int i = 0; i < lista.size(); i++) {
            //PRIMERO EXTRAO 
            vehVO = lista.get(i);

            productos[0] = vehVO.getVehPlaca();
            productos[1] = vehVO.getDatosId();
            productos[2] = vehVO.getCategoriaId();
            productos[3] = vehVO.getVehModelo();
            productos[4] = vehVO.getVehMarca();
            productos[5] = vehVO.getVehEstado();
            productos[6] = vehVO.getVehPrecio();
            modelo.addRow(productos);

        }

        Tabla.setModel(modelo);

    }

    public void listarCategoria() {
        CategoriaVO catVO = new CategoriaVO();
        CategoriaDAO catDAO = new CategoriaDAO();

        ArrayList<CategoriaVO> listaCategorias = catDAO.listar();
        for (int i = 0; i < listaCategorias.size(); i++) {
            catVO = listaCategorias.get(i);
            ComboxCat.addItem(catVO.getCatTipo());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        resultado = new javax.swing.JLabel();
        ButtonCategoria = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        ComboxCat = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 550));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(203, 239, 239));
        jPanel1.setLayout(null);

        Tabla.setBackground(new java.awt.Color(227, 248, 248));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLACA", "DATOS", "CATEGORIA", "MODELO", "MARCA", "ESTADO", "PRECIO"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 230, 720, 170);
        jPanel1.add(resultado);
        resultado.setBounds(40, 200, 430, 80);

        ButtonCategoria.setText("Consultar Por Categoria");
        ButtonCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonCategoria);
        ButtonCategoria.setBounds(420, 120, 170, 30);

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setText("CONSULTAR VEHICULO");
        jPanel1.add(titulo);
        titulo.setBounds(160, 30, 300, 60);

        ComboxCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione.." }));
        jPanel1.add(ComboxCat);
        ComboxCat.setBounds(150, 120, 220, 30);

        jLabel2.setText("CATEGORIA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 120, 70, 30);

        jButton1.setText("Volver al Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(790, 470, 120, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 950, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //        Menu menu = new Menu();
        //        menu.setVisible(true);
        //        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCategoriaActionPerformed
        String catId = String.valueOf(ComboxCat.getSelectedIndex());
        System.out.println(catId);

        VehiculoVO vehVO = new VehiculoVO();
        VehiculoDAO vehDAO = new VehiculoDAO();

        ArrayList<VehiculoVO> consultarCategoriaV = vehDAO.consultarporCategoria(catId);

        if (consultarCategoriaV.size() != 0) {
            JOptionPane.showMessageDialog(null, "Vehiculo consultado");
            ConsultarCategoria actualizarvehiculo = new ConsultarCategoria(consultarCategoriaV);
            actualizarvehiculo.setVisible(true);

            dispose();

        } else {
            resultado.setText("El Vehiculo NO existe");

        }
    }//GEN-LAST:event_ButtonCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarVehiculo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarVehiculo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarVehiculo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarVehiculo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCategoria;
    private javax.swing.JComboBox<String> ComboxCat;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
