
import ModeloDAO.DatosPDAO;
import ModeloVO.DatosPVO;
import ModeloVO.UsuarioVO;
import ModeloVO.VehiculoVO;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author usuario
 */
public class EditarPerfil extends javax.swing.JFrame {
    String idUsu;
    String datId;
    /**
     * Creates new form EditarPerfil
     */
    public  EditarPerfil(UsuarioVO usuVO) {
        initComponents();
        setLocationRelativeTo(null);
        idUsu = usuVO.getUsuId();

        DatosPVO datpVO = new DatosPVO();
        DatosPDAO datpDAO = new DatosPDAO();

        ArrayList<DatosPVO> listaDatos = datpDAO.listar(usuVO.getUsuId());
        for (int i = 0; i < listaDatos.size(); i++) {
            datpVO = listaDatos.get(i);
            textNombre.setText(datpVO.getDatNombre());
            textApellido.setText(datpVO.getDatApellido());
            textTelefono.setText(datpVO.getDatTelefono());
            textCorreo.setText(datpVO.getDatCorreo());
            datId = datpVO.getDatId();

    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textApellido = new javax.swing.JTextField();
        textTelefono = new javax.swing.JTextField();
        textCorreo = new javax.swing.JTextField();
        buttonActualzar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 550));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("EDITAR PERFIL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 30, 240, 60);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 130, 60, 20);

        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 190, 50, 20);

        jLabel4.setText("Telefono");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 250, 50, 20);

        jLabel5.setText("Correo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 310, 50, 20);
        getContentPane().add(textNombre);
        textNombre.setBounds(140, 120, 250, 30);
        getContentPane().add(textApellido);
        textApellido.setBounds(140, 180, 250, 30);
        getContentPane().add(textTelefono);
        textTelefono.setBounds(140, 240, 250, 30);
        getContentPane().add(textCorreo);
        textCorreo.setBounds(140, 300, 250, 30);

        buttonActualzar.setText("Actualizar");
        buttonActualzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActualzarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonActualzar);
        buttonActualzar.setBounds(600, 180, 90, 23);

        jButton1.setText("Volver al Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 220, 120, 23);

        resultado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(resultado);
        resultado.setBounds(30, 360, 690, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        Menu menu = new Menu();
//        menu.setVisible(true);
//        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonActualzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActualzarActionPerformed
        String daId = datId;
        String ususId = idUsu;
        String datNombre = String.valueOf(textNombre.getText());
        String datApellido = textApellido.getText();
        String datTipo = "";
        String datNumero = "";
        String datTelefono = textTelefono.getText();
        String datCorreo = textCorreo.getText();

        System.out.println(datNombre);
        System.out.println(datApellido);
        System.out.println(datTelefono);
        System.out.println(datCorreo);

        DatosPVO datpVO = new DatosPVO(daId, ususId, datNombre, datApellido, datTipo, datNumero, datTelefono, datCorreo);
        DatosPDAO datpDAO = new DatosPDAO(datpVO);

        if (datpDAO.actualizarRegistro()) {
            resultado.setText("Datos actualizados correctamente");
        } else {
            resultado.setText("Los datos NO se actualizaron correctamente");
        }
    }//GEN-LAST:event_buttonActualzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EditarPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonActualzar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel resultado;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextField textCorreo;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textTelefono;
    // End of variables declaration//GEN-END:variables
}
