
import Controlador.ControladorUsuario;
import ModeloDAO.UsuarioDAO;
import ModeloVO.UsuarioVO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author usuario
 */
public class IniciarSesion extends javax.swing.JFrame {

    ControladorUsuario controlador = new ControladorUsuario();

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonInicar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        textClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicar Sesión");
        setMinimumSize(new java.awt.Dimension(965, 550));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(203, 239, 239));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Iniciar Sesión");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 40, 270, 40);

        jButtonInicar.setText("Inicar Sesion");
        jButtonInicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInicar);
        jButtonInicar.setBounds(220, 330, 120, 30);

        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 250, 70, 14);

        textUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(textUsuario);
        textUsuario.setBounds(190, 170, 210, 30);

        jLabel2.setText("Usuario");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 170, 70, 20);
        jPanel1.add(resultado);
        resultado.setBounds(50, 390, 410, 90);
        jPanel1.add(textClave);
        textClave.setBounds(190, 240, 210, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 950, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicarActionPerformed
        String usuario = textUsuario.getText();
        String clave = textClave.getText();
        String id = "";

        System.out.println(usuario);
        System.out.println(clave);

        UsuarioVO usuVO = new UsuarioVO(id, usuario, clave);
        UsuarioDAO usuDAO = new UsuarioDAO(usuVO);

        ArrayList<UsuarioVO> listaRol = new ArrayList<>();
        if (usuDAO.iniciarSesion(usuario, clave)) {

            UsuarioDAO usuarioDAO = new UsuarioDAO();
            listaRol = usuarioDAO.rol(usuario);
            for (int i = 0; i < listaRol.size(); i++) {
                usuVO = listaRol.get(i);
            }
            //JOptionPane.showMessageDialog(null, "Bienvenido: " + usuario + " ¿deseas actualizar  perfil?");
            if (listaRol.size() > 1) {

                Menu menu = new Menu(usuario);
                menu.setVisible(true);
                dispose();

            } else if (usuVO.getRol().equals("Vendedor")) {
                int opcion = JOptionPane.showConfirmDialog(null, "¿Deseas actualizar tu perfil?");

                if (JOptionPane.OK_OPTION == opcion) {
                    EditarPerfil editarperfil = new EditarPerfil(usuVO);
                    editarperfil.setVisible(true);
                    dispose();

                } else {
                    JOptionPane.showMessageDialog(null, "Bienvenido: " + usuario);
                    controlador.rolVendedor();
                    dispose();
                }

            } else {
                JOptionPane.showMessageDialog(null, "Bienvenido: " + usuario);
                controlador.rolComprador();
                dispose();
            }

            String usuId = usuVO.getUsuId();
            System.err.println(usuId);

        } else {
            resultado.setText("El usuario y/o la contraseña son incorrectas");
        }
//            resultado.setText("Bienvenid@");
//            JOptionPane.showMessageDialog(null, "Bienvenido");
//            Menu menu = new Menu(usuario);
//            menu.setVisible(true);
//            dispose();

    }//GEN-LAST:event_jButtonInicarActionPerformed

    private void textUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textUsuarioKeyTyped
        //VALIDACION DE CAMPOS
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "En este campo solo se permiten letras ");

        }
    }//GEN-LAST:event_textUsuarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInicar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultado;
    private javax.swing.JPasswordField textClave;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
