
import Controlador.ControladorUsuario;
import ModeloDAO.UsuarioDAO;
import ModeloVO.UsuarioVO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class Menu extends javax.swing.JFrame {
    ControladorUsuario controlador = new ControladorUsuario();
        String idUsu;
    /**
     * Creates new form Menu
     */
    public Menu(String usuario) {
          initComponents();
          setLocationRelativeTo(null);
          nombre.setText(usuario);

          UsuarioVO usuVO = new UsuarioVO();
          UsuarioDAO usuDAO = new UsuarioDAO();
          
          ArrayList<UsuarioVO> listaRol = usuDAO.rol(usuario);
          for (int i = 0; i < listaRol.size(); i++) {
              usuVO = listaRol.get(i);
                      ComboxRol.addItem(usuVO.getRol());
            idUsu=usuVO.getUsuId();
        }
          
          
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        CerrarSesion = new javax.swing.JButton();
        RegistrarV = new javax.swing.JButton();
        RegistrarU = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ActulizarU = new javax.swing.JButton();
        ConsultarVP = new javax.swing.JButton();
        ActualizarV = new javax.swing.JButton();
        ComboxRol = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        editarperfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setMinimumSize(new java.awt.Dimension(950, 550));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(203, 239, 239));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel2.setLayout(null);

        CerrarSesion.setText("Cerrar Sesion");
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(CerrarSesion);
        CerrarSesion.setBounds(620, 720, 130, 30);

        RegistrarV.setBackground(new java.awt.Color(243, 245, 118));
        RegistrarV.setText("Registrar Vehiculo");
        RegistrarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarVActionPerformed(evt);
            }
        });
        jPanel2.add(RegistrarV);
        RegistrarV.setBounds(90, 200, 130, 30);

        RegistrarU.setText("Registrar Usuario");
        RegistrarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarUActionPerformed(evt);
            }
        });
        jPanel2.add(RegistrarU);
        RegistrarU.setBounds(360, 200, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("USUARIO");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(390, 160, 60, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("CONSENCIONARIO DE VEHICULO");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(260, 70, 650, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("VEHICULO");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(110, 160, 80, 30);

        ActulizarU.setBackground(new java.awt.Color(243, 245, 118));
        ActulizarU.setText("Actualizar Usuario");
        ActulizarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActulizarUActionPerformed(evt);
            }
        });
        jPanel2.add(ActulizarU);
        ActulizarU.setBounds(360, 260, 130, 30);

        ConsultarVP.setBackground(new java.awt.Color(243, 245, 118));
        ConsultarVP.setText("Consultar");
        ConsultarVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarVPActionPerformed(evt);
            }
        });
        jPanel2.add(ConsultarVP);
        ConsultarVP.setBounds(90, 260, 130, 30);

        ActualizarV.setText("Actualizar ");
        jPanel2.add(ActualizarV);
        ActualizarV.setBounds(90, 310, 130, 30);

        ComboxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        jPanel2.add(ComboxRol);
        ComboxRol.setBounds(20, 40, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ROL");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 10, 50, 20);

        jButton1.setText("Cambiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(190, 40, 110, 30);
        jPanel2.add(nombre);
        nombre.setBounds(720, 20, 200, 50);

        editarperfil.setText("Editar Perfil");
        editarperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarperfilActionPerformed(evt);
            }
        });
        jPanel2.add(editarperfil);
        editarperfil.setBounds(360, 313, 130, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 950, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarVActionPerformed
       RegistrarVehiculo vehiculocontrolador = new RegistrarVehiculo(idUsu);
       vehiculocontrolador.setVisible(true);
       dispose();
       
        
    }//GEN-LAST:event_RegistrarVActionPerformed

    private void ConsultarVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarVPActionPerformed
        ConsultarVehiculo consultar = new ConsultarVehiculo();
        consultar.setVisible(true);
        dispose();
    }//GEN-LAST:event_ConsultarVPActionPerformed

    private void ActulizarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActulizarUActionPerformed
        ActualizarUsuario actualizarusuario = new ActualizarUsuario();
        actualizarusuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_ActulizarUActionPerformed

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(ComboxRol.getSelectedItem().equals("Vendedor")){
            controlador.rolVendedor();
            dispose();
            
        }else if(ComboxRol.getSelectedItem().equals("Comprador")){
            controlador.rolComprador();
            dispose();
            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione un rol");
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RegistrarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarUActionPerformed
        RegistrarUsuario registrarusuario = new RegistrarUsuario();
        registrarusuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegistrarUActionPerformed

    private void editarperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarperfilActionPerformed
        UsuarioVO usuVO = new UsuarioVO();
        
        
        EditarPerfil editar = new EditarPerfil(usuVO);
        editar.setVisible(true);
        dispose();
    }//GEN-LAST:event_editarperfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          //new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarV;
    private javax.swing.JButton ActulizarU;
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JComboBox<String> ComboxRol;
    private javax.swing.JButton ConsultarVP;
    private javax.swing.JButton RegistrarU;
    private javax.swing.JButton RegistrarV;
    private javax.swing.JButton editarperfil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
