
import ModeloDAO.CategoriaDAO;
import ModeloDAO.DatosPDAO;
import ModeloDAO.VehiculoDAO;
import ModeloVO.CategoriaVO;
import ModeloVO.DatosPVO;
import ModeloVO.VehiculoVO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author usuario
 */
public class RegistrarVehiculo extends javax.swing.JFrame {
    String usuId;
    /**
     * Creates new form VehiculoControlador
     */
    public RegistrarVehiculo(String idUsu) {
        initComponents();
        setLocationRelativeTo(null);
        usuId = idUsu;
        
        DatosPVO datpVO = new DatosPVO();
        DatosPDAO datpDAO = new DatosPDAO();
        
        datpVO=datpDAO.consultarDatos(usuId);
        usuId=datpVO.getDatId();

        CategoriaVO catVO = new CategoriaVO();
        CategoriaDAO catDAO = new CategoriaDAO();

        ArrayList<CategoriaVO> listaCategorias = catDAO.listar();
        for (int i = 0; i < listaCategorias.size(); i++) {
            catVO = listaCategorias.get(i);
            ComboxCat.addItem(catVO.getCatTipo());
        }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        textModelo = new javax.swing.JTextField();
        marca = new javax.swing.JLabel();
        textMarca = new javax.swing.JTextField();
        modelo = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        textPrecio = new javax.swing.JTextField();
        buttonRegistrar = new javax.swing.JButton();
        ComboxCat = new javax.swing.JComboBox<>();
        modelo1 = new javax.swing.JLabel();
        modelo2 = new javax.swing.JLabel();
        ComboxEstado = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        textResultado = new javax.swing.JLabel();
        textPlaca = new javax.swing.JTextField();
        placa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vehiculo");
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setText("REGISTRO DE VEHICULOS ");
        getContentPane().add(titulo);
        titulo.setBounds(80, 10, 330, 60);

        textModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textModeloKeyTyped(evt);
            }
        });
        getContentPane().add(textModelo);
        textModelo.setBounds(180, 200, 240, 30);

        marca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        marca.setText("Categoria");
        getContentPane().add(marca);
        marca.setBounds(80, 160, 80, 30);

        textMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textMarcaKeyTyped(evt);
            }
        });
        getContentPane().add(textMarca);
        textMarca.setBounds(180, 240, 240, 30);

        modelo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        modelo.setText("Estado");
        getContentPane().add(modelo);
        modelo.setBounds(80, 280, 80, 30);

        color.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        color.setText("Precio");
        getContentPane().add(color);
        color.setBounds(80, 320, 80, 30);

        textPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPrecioKeyTyped(evt);
            }
        });
        getContentPane().add(textPrecio);
        textPrecio.setBounds(180, 320, 240, 30);

        buttonRegistrar.setText("Registrar");
        buttonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRegistrar);
        buttonRegistrar.setBounds(340, 380, 90, 30);

        ComboxCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione.." }));
        getContentPane().add(ComboxCat);
        ComboxCat.setBounds(180, 170, 210, 20);

        modelo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        modelo1.setText("Modelo");
        getContentPane().add(modelo1);
        modelo1.setBounds(80, 200, 80, 30);

        modelo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        modelo2.setText("Marca");
        getContentPane().add(modelo2);
        modelo2.setBounds(80, 240, 80, 30);

        ComboxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NUEVO", "USADO" }));
        getContentPane().add(ComboxEstado);
        ComboxEstado.setBounds(180, 290, 200, 20);

        jPanel2.setBackground(new java.awt.Color(203, 239, 239));
        jPanel2.setLayout(null);

        jButton1.setText("Volver al Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(330, 420, 120, 30);
        jPanel2.add(textResultado);
        textResultado.setBounds(40, 400, 310, 60);
        jPanel2.add(textPlaca);
        textPlaca.setBounds(180, 120, 240, 30);

        placa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        placa.setText("Placa");
        jPanel2.add(placa);
        placa.setBounds(80, 120, 80, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 950, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarActionPerformed
        String vehPlaca = textPlaca.getText();
        String datId = usuId;
       
        String catId = String.valueOf(ComboxCat.getSelectedIndex());
        String vehModelo = textModelo.getText();
        String vehMarca = textMarca.getText();
        String vehEstado = String.valueOf(ComboxEstado.getSelectedItem());
        String vehPrecio = textPrecio.getText();

        System.out.println(vehPlaca);
        System.out.println(datId);
        System.out.println(catId);
        System.out.println(vehModelo);
        System.out.println(vehMarca);
        System.out.println(vehEstado);
        System.out.println(vehPrecio);

        VehiculoVO vehVO = new VehiculoVO(vehPlaca, datId, catId, vehModelo, vehMarca, vehEstado, vehPrecio);
        VehiculoDAO vehDAO = new VehiculoDAO(vehVO);
        
        vehVO = vehDAO.consultarPlaca(vehPlaca);
        if (vehVO == null){
            if (vehDAO.agregarRegistro()) {
            textResultado.setText("El vehiculo se registro correctamente");
        } else {
            textResultado.setText("El vehiculo NO se registro correctamente");
            }
        } else{
            textResultado.setText("El vehiculo con esa placa ya esta registrado");
        }
            
        
        
        
    }//GEN-LAST:event_buttonRegistrarActionPerformed

    private void textModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textModeloKeyTyped
           char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "En este campo solo se permiten numeros ");

        }
    }//GEN-LAST:event_textModeloKeyTyped

    private void textPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPrecioKeyTyped
           char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "En este campo solo se permiten numeros ");

        }
    }//GEN-LAST:event_textPrecioKeyTyped

    private void textMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMarcaKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "En este campo solo se permiten letras ");

        }
    }//GEN-LAST:event_textMarcaKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        Menu menu = new Menu();
//        menu.setVisible(true);
//        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new RegistrarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboxCat;
    private javax.swing.JComboBox<String> ComboxEstado;
    private javax.swing.JButton buttonRegistrar;
    private javax.swing.JLabel color;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel marca;
    private javax.swing.JLabel modelo;
    private javax.swing.JLabel modelo1;
    private javax.swing.JLabel modelo2;
    private javax.swing.JLabel placa;
    private javax.swing.JTextField textMarca;
    private javax.swing.JTextField textModelo;
    private javax.swing.JTextField textPlaca;
    private javax.swing.JTextField textPrecio;
    private javax.swing.JLabel textResultado;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
